# Name of the workflow
name: update-trendbreaker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch, as well as 1200 every day
on:
#  push:
#    branches: [ main ]
#  release:
#    types: [ published ]
  schedule:
     - cron:  '3 16,17 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Important: ubuntu-latest is not set up properly for R, so use macOS
jobs:
  update-trendbreaker:
    runs-on: macos-latest
    env:
      PHIFUNC_TOKEN: ${{ secrets.PHIFUNC_TOKEN }}
    steps:
      - name: Checkout repos
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v1
    
      - name: Install dependencies
        run: |
          Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
          options(install.packages.check.source = "no")
          pkgs <- c("remotes", "here", "ISOweek")
          install.packages(pkgs, repos = "https://cloud.r-project.org/")
          remotes::install_github("reconhub/reportfactory", upgrade = "never")
          remotes::install_github("reconhub/rfextras", upgrade = "never")
          reportfactory::install_deps(factory = "factory", upgrade = "never")
          remotes::install_github("reconhub/incidence2", upgrade = "never")
          remotes::install_github("reconhub/trendbreaker", upgrade = "never")
        shell: Rscript {0}
 
      - name: Install deps of the factory and compile data report
        run: |
          source("run_remote_data.R")
          source("run_remote_trendbreaker.R")
        shell: Rscript {0}
        
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/clean/asmodee*
          git commit -m "Automatic update of trendbreaker results"
      
      - name: Push files
        run: |
          git push
 